version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly

    groups:
      test-dependencies:
        patterns:
          - "pytest*"
          - "pandas"
          - "pyarrow"
          - "brotli"

      build-dependencies:
        patterns:
          - "setuptools"
          - "wheel"
          - "Cython"
          - "numpy"